-- jra_payoutsテーブルに全ての払い戻し関連カラムを追加
-- 既存のテーブル構造を保持しつつ、不足しているカラムを追加

-- 単勝
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 単勝_馬番 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 単勝_払戻 INT;

-- 複勝
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 複勝_馬番_1 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 複勝_払戻_1 INT,
ADD COLUMN IF NOT EXISTS 複勝_馬番_2 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 複勝_払戻_2 INT,
ADD COLUMN IF NOT EXISTS 複勝_馬番_3 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 複勝_払戻_3 INT;

-- 馬連
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 馬連_馬番 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 馬連_払戻 INT;

-- ワイド
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS ワイド_馬番_1 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_1 INT,
ADD COLUMN IF NOT EXISTS ワイド_馬番_2 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_2 INT,
ADD COLUMN IF NOT EXISTS ワイド_馬番_3 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_3 INT;

-- 馬単
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 馬単_馬番 VARCHAR(10),
ADD COLUMN IF NOT EXISTS 馬単_払戻 INT;

-- 三連複
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 三連複_馬番 VARCHAR(20),
ADD COLUMN IF NOT EXISTS 三連複_払戻 INT;

-- 三連単
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 三連単_馬番 VARCHAR(20),
ADD COLUMN IF NOT EXISTS 三連単_払戻 INT;

-- メタデータ
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS 取得日時 TIMESTAMP;

-- インデックスを追加（検索性能向上）
CREATE INDEX IF NOT EXISTS idx_jra_payouts_race_id ON jra_payouts(race_id);