-- jra_payoutsテーブルにワイド関連のカラムを追加
ALTER TABLE jra_payouts
ADD COLUMN IF NOT EXISTS ワイド_馬番_1 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_1 INT,
ADD COLUMN IF NOT EXISTS ワイド_馬番_2 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_2 INT,
ADD COLUMN IF NOT EXISTS ワイド_馬番_3 VARCHAR(10),
ADD COLUMN IF NOT EXISTS ワイド_払戻_3 INT,
ADD COLUMN IF NOT EXISTS 取得日時 TIMESTAMP;